version: "3.8"

volumes:
  school_library_db:

services:
  ams-database:
    image: postgres:14.4-alpine
    restart: unless-stopped
    container_name: db.school_library.com
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      retries: 3
    ports:
      - "5439:5432"
    volumes:
      - school_library_db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: school_library
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: dgb123

